backend:
  name: github
  repo: changrun1/changrun1.github.io
  branch: main
  base_url: https://quiet-water-7883.chang71505.workers.dev
  auth_endpoint: /cms/auth
  preview_context: github_pages
publish_mode: editorial_workflow
locale: zh_Hant
site_url: https://changrun1.github.io/
logo_url: /profile-placeholder.svg
media_folder: public/media
public_folder: /media
slug:
  encoding: unicode
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: posts
    label: 文章
    folder: content/posts
    create: true
    slug: '{{slug}}'
    preview_path: posts/{{slug}}
    fields:
      - { label: 標題, name: title, widget: string }
      - { label: 摘要, name: excerpt, widget: text, required: false }
      - { label: 分類, name: category, widget: string, default: 'Note' }
      - { label: 標籤, name: tags, widget: list, required: false, field: { label: 標籤, name: tag, widget: string } }
      - { label: 更新時間, name: updatedAt, widget: datetime, format: 'YYYY-MM-DDTHH:mm:ss.SSSZ', required: false }
      - { label: 外部連結, name: externalUrl, widget: string, required: false }
      - { label: 內容, name: body, widget: markdown }
  - name: projects
    label: 作品集
    files:
      - file: content/projects/index.json
        label: 作品
        name: index
        fields:
          - label: 作品列表
            name: projects
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: 短網址, name: slug, widget: string }
              - { label: 標題, name: title, widget: string }
              - { label: 描述, name: description, widget: text }
              - { label: 類型, name: type, widget: string }
              - { label: 技術標籤, name: tech, widget: list, field: { label: 技術, name: tech, widget: string } }
              - { label: 專案網址, name: url, widget: string, required: false }
              - { label: 原始碼, name: repo, widget: string, required: false }
              - { label: 封面圖, name: cover, widget: string, required: false }
              - { label: 更新時間, name: updatedAt, widget: datetime, format: 'YYYY-MM-DDTHH:mm:ss.SSSZ', required: false }
  - name: profile
    label: 個人資料
    files:
      - file: content/profile/profile.json
        label: 基本檔案
        name: profile
        fields:
          - { label: 姓名, name: name, widget: string }
          - { label: 頭銜, name: headline, widget: string }
          - { label: 摘要, name: summary, widget: text }
          - { label: 所在地, name: location, widget: string }
          - label: 聯絡連結
            name: contactLinks
            widget: list
            summary: '{{fields.label}}'
            fields:
              - { label: 顯示文字, name: label, widget: string }
              - { label: 連結, name: href, widget: string }
